#!/bin/bash

python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_simulator.txt Simulator 8192 0  &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_corrected_simulator.txt Simulator 8192 0 &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_athens.txt Athens 8192 0 &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_ibmqx2.txt Yorktown 8192 0 &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_melbourne.txt Melbourne 8192 0 &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_ourense.txt Ourense 8192 0 &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_santiago.txt Santiago 8192 0 &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_valencia.txt Valencia 8192 0 &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_vigo.txt Vigo 8192 0 &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_corrected_athens.txt Athens 8192 0 &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_corrected_ibmqx2.txt Yorktown 8192 0 &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_corrected_melbourne.txt Melbourne 8192 0 &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_corrected_ourense.txt Ourense 8192 0 &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_corrected_santiago.txt Santiago 8192 0 &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_corrected_valencia.txt Valencia 8192 0 &
python equator_plotter.py  PhaseCovariant/IBM/OnlyEquator/results_corrected_vigo.txt Vigo 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_simulator.txt Simulator 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_corrected_simulator.txt Simulator 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_athens.txt Athens 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_ibmqx2.txt Yorktown 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_melbourne.txt Melbourne 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_ourense.txt Ourense 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_santiago.txt Santiago 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_valencia.txt Valencia 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_vigo.txt Vigo 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_corrected_athens.txt Athens 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_corrected_ibmqx2.txt Yorktown 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_corrected_melbourne.txt Melbourne 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_corrected_ourense.txt Ourense 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_corrected_santiago.txt Santiago 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_corrected_valencia.txt Valencia 8192 0 &
python equator_plotter.py  Economical/IBM/OnlyEquator/results_corrected_vigo.txt Vigo 8192 0 &
python equator_plotter.py  PhaseCovariant/Starmon/OnlyEquator/results_starmon.txt Starmon-5 16384 0 &
python equator_plotter.py  PhaseCovariant/Starmon/OnlyEquator/results_starmon_corrected.txt Starmon-5 16384 0 &
python equator_plotter.py  Economical/Starmon/OnlyEquator/results_starmon.txt Starmon-5 16384 0 &
python equator_plotter.py  Economical/Starmon/OnlyEquator/results_starmon_corrected.txt Starmon-5 16384 0 &
python equator_plotter.py  Economical/Spin2/FullSphere/results_spin2.txt Spin-2 4096 0 &
python equator_plotter.py  Economical/Spin2/FullSphere/results_spin2_corrected.txt Spin-2 4096 0